### PR TITLE
docs: verbiage and examples update

### PR DESCRIPTION
**Pull request by adamwolfe-tc**
# ↪️ Pull Request

- [x] Make sure you are opening from a **feature/feat/docs/fix/bug/hotfix/stable/chore** (right side) and not your master branch!
- [x] Ensure that the pull request title represents the desired changelog entry

## 📒 Description

I wrote a similar module for work and would prefer to use something official but upon pulling this module I found it would not work with the examples given and their are many references to `GitHub` and related `GitHub` terms.

This PR replaces those with the GitLab terminology as well as updates a few things to get it passing all `precommit` checks.  also a small modernization of the example CI/CD yaml.

## 🕶️ Types of changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [x] Enhancement/optimization # kinda?
- [x] Documentation
- [ ] Dependencies

### 🤯 List of changes

1.  there are several mentions of `GitHub` and `GitHub Actions` in this code base.  I've replaced those with `GitLab` and `Gitlab Pipelines`.

2.  this PR also replaces `repos`, `repository`, `repositories` and `organizations` with the proper GitLab equivalents of `projects` and `namespaces`

3.  it includes the `terraform-docs` updates that come from running `pre-commit`

4.  corrects the description of the `basic` example and cleans up example code

5.   updates gitlab cicd yaml example to use the new OIDC tokens.  `CI_JOB_JWT*` variables are deprecated and will be removed in v17.

6.  updates instances of `.*.` and `.0.` with `[*].` and `[0].`, removes "interpolation-only" expressions as per precommit tflint rules

7.  renamed a couple variables to match gitlab terminology e.g. `repositories` -> `projects`

8.  added some variable descriptions, again `precommit` stuff

9.  renamed `repositories` variable to `project_paths` since the check expects `project_path:` in the regex.  updated examples to be like `["project_path:foo/bar", "project_path:baz/quk"]` to match

10.  removes unused `gitlab_url` variable.  (`url` is what is currently used)

## 🚨 Test instructions

this can be pulled and applied as is.

## Checklist

- [x] My code follows the code style of this project.
- [ ] I have read the [**CONTRIBUTING** document](../contributing.md).  # there isn't one?
- [ ] Added/updated unit tests for this change
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).
- [x] Filled out test instructions (In case there aren't any unit tests)
- [x] I followed the existing code standards and didn't mess up the formatting.  # i did run `terraform fmt`
- [x] My change requires a change to the documentation.
- [x] I did my best to add documentation to any public classes or methods I added.
- [ ] Included links to related issues/PRs

### CODE REVIEW

**Comment by adamwolfe-tc** [comment]
i don't understand why the naming check fails.  it says : 

```
Available types:
 - fix
 - feat
 - docs
 - ci
 - chore
```

and this branch's name starts with `docs/`

**Comment by adamwolfe-tc** [comment]
@ivankatliarchuk any consideration or feedback here?

**Comment by kushmansingh** [comment]
Thank you for this, the `project_path:` prefix tripped me up

**Comment by adamwolfe-tc** [comment]
any plans on using this or declining?  i'm on hold for a project at work.  I can go back to the module i wrote previously but i'd prefer to contribute to this if that's an option.

**Pull request merged**
